### ISSUE TITLE
seek doesn't work

### ISSUE THREAD

**Issue by yakir12** [kmsquire/VideoIO.jl#105]
Tried the example code from the readme. Didn't work. The seek functionality would be awesome for my application, maybe I can help?
```julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0 (2017-06-19 13:05 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> using Images

julia> import ImageView

julia> import VideoIO

WARNING: deprecated syntax "abstract StreamContext" at /home/yakir/.julia/v0.6/VideoIO/src/avio.jl:16.
Use "abstract type StreamContext end" instead.

julia> f = VideoIO.openvideo("some_example_video.mp4")
WARNING: Array{T}(::Type{T}, m::Integer, n::Integer, o::Integer) is deprecated, use Array{T}(Int(m), Int(n), Int(o)) instead.
Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:70
 [2] Array(::Type{UInt8}, ::Int32, ::Int32, ::Int32) at ./deprecated.jl:57
 [3] #VideoReader#4(::Bool, ::Int64, ::Int32, ::Type{T} where T, ::VideoIO.AVInput{String}, ::Int64) at /home/yakir/.julia/v0.6/VideoIO/src/avio.jl:322
 [4] #VideoReader#5(::Array{Any,1}, ::Type{T} where T, ::String) at /home/yakir/.julia/v0.6/VideoIO/src/avio.jl:368
 [5] VideoIO.VideoReader(::String) at /home/yakir/.julia/v0.6/VideoIO/src/avio.jl:368
 [6] #openvideo#6(::Array{Any,1}, ::Function, ::String, ::Vararg{String,N} where N) at /home/yakir/.julia/v0.6/VideoIO/src/avio.jl:486
 [7] openvideo(::String, ::Vararg{String,N} where N) at /home/yakir/.julia/v0.6/VideoIO/src/avio.jl:486
 [8] eval(::Module, ::Any) at ./boot.jl:235
 [9] eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:66
 [10] macro expansion at ./REPL.jl:97 [inlined]
 [11] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:73
while loading no file, in expression starting on line 0
VideoReader(...)

julia> seek(f,1)
ERROR: MethodError: no method matching seek(::VideoIO.VideoReader{true}, ::Int64)
Closest candidates are:
  seek(::IOStream, ::Integer) at iostream.jl:48
  seek(::Base.AbstractIOBuffer, ::Integer) at iobuffer.jl:165
  seek(::Base.Libc.FILE, ::Integer) at libc.jl:86
  ...
```

**Comment by romainFr** [comment]
It's because seek is a little picky for now and expects a Float for the position to seek. In your example, seek(f,1.0) should work.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by yakir12** [comment]
Hmm, still doesn't work:
```julia
julia> seek(f,1.0)
ERROR: MethodError: no method matching seek(::VideoIO.VideoReader{true}, ::Float64)
```
Might be best to set the argument's type to some temporal unit (e.g. `Dates.Nanosecond`)

**Comment by timholy** [comment]
You'll need `Pkg.checkout("VideoIO")`; I don't think there's been a release that includes the seek functionality.

**Comment by yakir12** [comment]
Can confirm, thanks Tim. 

Do you guys want me to PR some of this stuff? Like the documents could mention this, and the type of the arguments to `seek`?

**Comment by kmsquire** [comment]
@yakir12, that would be great, thanks!

**Comment by yakir12** [comment]
Right, made a PR just for the README. 

As to setting `seek`'s `second` argument's type to `Second`, I quickly realized what a rabbit-hole this might be. Looks like you've implemented a custom Rational type. I'm reluctant to change any of this before understanding why you didn't use the native rational type in Julia...

**Comment by kmsquire** [comment]
> Looks like you've implemented a custom Rational type. I'm reluctant to change any of this before understanding why you didn't use the native rational type in Julia.

The ffmpeg/libav libraries implement this type; what you see in the code is the automatically generated version of the type defined in the header files.

It's probably the case that a Rational{Int32} would work, but I've never tested it.
