### ISSUE TITLE
WORD_SIZE is not defined

### ISSUE THREAD

**Issue by hearnsj** [kmsquire/VideoIO.jl#116]
I am sure I will get this issue sorted out quickly.
I am just flagging it up in case anyone else sees the same thing.
I use Windows 10 on a 64 bit laptop and decided to do a clean install of Julia 0.62
Then on the fresh install:

pkg.add("WinRPM")
pkg.add("Gtk")
pkg.add(""ImageView")
pkg.add("VideoIO")

I then get this error:
INFO: Building Gtk
INFO: Nothing to do
INFO: Updating WinRPM package list
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Building VideoIO
===================================================[ ERROR: VideoIO ]===================================================

LoadError: UndefVarError: WORD_SIZE not defined
while loading C:\Users\hearn\.julia\v0.6\VideoIO\deps\build.jl, in expression starting on line 30

========================================================================================================================

====================================================[ BUILD ERRORS ]====================================================

WARNING: VideoIO had build errors.

 - packages with build errors remain installed in C:\Users\hearn\.julia\v0.6
 - build the package(s) and all dependencies with `Pkg.build("VideoIO")`
 - build a single package by running its `deps/build.jl` script

========================================================================================================================
INFO: Package database updated

**Comment by hearnsj** [comment]
Nope, I run
Pkg.build(""VideoIO")
Still the same: LoadError: UndefVarError: WORD_SIZE not defined

I know this is a general Julia problem, not really VideoIO

**Comment by hearnsj** [comment]
I asked on Julia Discourse

**Comment by Jacob-Stevens-Haas** [comment]
I believe WORD_SIZE is deprecated, and build.jl needs to change to Sys.WORD_SIZE.

Also, the link to download ffmpeg needs to be pointed to https://ffmpeg.zeranoe.com/builds/win$(Sys.WORD_SIZE)/static/ffmpeg-3.4.2-win$(Sys.WORD_SIZE)-static.zip (or something else if you're reading this later).  In the current version of build.jl, it uses different folder names and a 7z file that 404's.

I also changed line 98 to refer to the newer version of ffmpeg
`provides(Sources,
         URI("http://www.ffmpeg.org/releases/ffmpeg-3.4.2.tar.gz"),
         libav_libs)`

These changes make build.jl move further down execution, but I'm still getting stuck on "LoadError: Provider BinDeps.RemoteBinaries failed to satisfy dependency libavcodec"

**Comment by balthazar314** [comment]
I've changed the URI to `URI("https://ffmpeg.zeranoe.com/builds/win$(Sys.WORD_SIZE)/shared/ffmpeg-3.4.2-win$(Sys.WORD_SIZE)-shared.zip")`, I think you need the "shared" because that version includes shared libraries that the package depends on. also on lines 7 though 8 you need to add correct version numbers to the lists of aliases, for instance I added "57" to the array because by av codac lib is `avcodac-57.dll`
`aliases=[["libavcodec-ffmpeg.so.","libavcodec.","libavcodec.so.","libavcodec.ffmpeg.so.","avcodec-"].*["53" "54" "55" "56" "57"]...`
you also need to do this for your other deps 
```
deps = [
    libavcodec = library_dependency("libavcodec", aliases=[["libavcodec-ffmpeg.so.","libavcodec.","libavcodec.so.","libavcodec.ffmpeg.so.","avcodec-"].*["53" "54" "55" "56" "57"]...], group = group)
    libavformat = library_dependency("libavformat", aliases=[["libavformat-ffmpeg.so.","libavformat.","libavformat.so.","libavformat.ffmpeg.so.","avformat-"].*["53" "54" "55" "56" "57"]...], group = group)
    libavutil = library_dependency("libavutil", aliases=[["libavutil-ffmpeg.so.", "libavutil.","libavutil.so.", "libavutil.ffmpeg.so.", "avutil-"].*["53" "54" "55" "56" "57"]...], group = group)
    libswscale = library_dependency("libswscale", aliases=[["libswscale-ffmpeg.so.","libswscale.","libswscale.so.","libswscale.ffmpeg.so.","swscale-"].*["2" "3" "4"]...], group = group)
    libavfilter = library_dependency("libavfilter", aliases=[["libavfilter-ffmpeg.so.","libavfilter.","libavfilter.so.","libavfilter.ffmpeg.so.","avfilter-"].*["2" "3" "4" "5" "6"]...], group = group)
    libavdevice = library_dependency("libavdevice", aliases=[["libavdevice-ffmpeg.so.","libavdevice.","libavdevice.so.","libavdevice.ffmpeg.so.","avdevice-"].*["53" "54" "55" "56" "57"]...], group = group)
]
```

**Comment by hearnsj** [comment]
Closing this issue.  Can we continue on Issue 128 ?
https://github.com/kmsquire/VideoIO.jl/issues/128
