### ISSUE TITLE
Install on 1.0.1 WORD_SIZE is not defined

### ISSUE THREAD

**Issue by hearnsj** [kmsquire/VideoIO.jl#128]
I know VideoIO is not ready for 1.0 yet - but I would like to help get it running.
On Windows 10 and Julia 1.0.1  I can get Gtk and Images.jl installed by adding the latest \master version
When I build  VideoIOO#master I get an error abot WORD_SIZE as below.
But WORD_SIZE is defined. Clearly that constant is not getting through to the build scripts.

ulia> versioninfo()
Julia Version 1.0.1
Commit 0d713926f8 (2018-09-29 19:05 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)

[d6d074c3] + VideoIO v0.4.0+ #master (https://github.com/kmsquire/VideoIO.jl.git)
  Building VideoIO → `C:\Users\hearn\.julia\packages\VideoIO\PIgWQ\deps\build.log`
┌ Error: Error building `VideoIO`:
│ ERROR: LoadError: UndefVarError: WORD_SIZE not defined
│ Stacktrace:
│  [1] top-level scope at C:\Users\hearn\.julia\packages\VideoIO\PIgWQ\deps\build.jl:29
│  [2] include at .\boot.jl:317 [inlined]
│  [3] include_relative(::Module, ::String) at .\loading.jl:1041
│  [4] include(::Module, ::String) at .\sysimg.jl:29
│  [5] include(::String) at .\client.jl:388
│  [6] top-level scope at none:0
│ in expression starting at C:\Users\hearn\.julia\packages\VideoIO\PIgWQ\deps\build.jl:28
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Pkg\src\Operations.jl:1069

**Comment by hearnsj** [comment]
Ah - I of course flagged up the same problem in Issue 116 https://github.com/kmsquire/VideoIO.jl/issues/116

**Comment by hearnsj** [comment]
In build.jl the incorrect file is being downloaded for ffmpeg.
The zeranoe website has changed to ffmpeg-latest
Also there is a change to zip rather than 7z  - I cannot get this to unpack. Should Builddeps do this automatically?

if Sys.iswindows()
    WORD_SIZE=64
#    provides(Binaries, URI("http://ffmpeg.zeranoe.com/builds/win$WORD_SIZE/shared/ffmpeg-2.2.3-win$WORD_SIZE-shared.7z"),
    provides(Binaries, URI("http://ffmpeg.zeranoe.com/builds/win$WORD_SIZE/shared/ffmpeg-latest-win$WORD_SIZE-shared.zip"),
             libav_libs,
             os = :Windows,
             unpacked_dir="ffmpeg-2.2.3-win$WORD_SIZE-shared/bin")
end

**Comment by hearnsj** [comment]
Sorry - bad formatting
``if Sys.iswindows()
#    provides(Binaries, URI("http://ffmpeg.zeranoe.com/builds/win$WORD_SIZE/shared/ffmpeg-2.2.3-win$WORD_SIZE-shared.7z"),
    provides(Binaries, URI("http://ffmpeg.zeranoe.com/builds/win$WORD_SIZE/shared/ffmpeg-latest-win$WORD_SIZE-shared.zip"),
             libav_libs,
             os = :Windows,
#             unpacked_dir="ffmpeg-2.2.3-win$WORD_SIZE-shared/bin")
             unpacked_dir="ffmpeg-latest-win$WORD_SIZE-shared/bin")
end

**Comment by ianshmean** [comment]
This should be fixed in master now thanks to https://github.com/kmsquire/VideoIO.jl/pull/135
