### ISSUE TITLE
looping through video

### ISSUE THREAD

**Issue by SimonDanisch** [kmsquire/VideoIO.jl#58]
Hi,
is there something like seekstart?!
I'm trying to get this running:
```Julia
function play{T}(buffer::Array{T, 2}, video_stream, t)
	eof(video_stream) && seekstart(video_stream)
	w,h = size(buffer)
	buffer = reinterpret(Uint8, buffer, (3, w,h))
	read!(video_stream, buffer) # looses type and shape
	return reinterpret(T, buffer, (w,h))
end
```
I currently do this with reopening the file :(

Best,
Simon

**Comment by kmsquire** [comment]
Hi Simon, I added a seekstart method in the ["kms/seekstart" branch](https://github.com/kmsquire/VideoIO.jl/tree/kms/seekstart).  

It's not quite right yet--we need to tell ffmpeg to clear its internal buffers first--but it might work fine for your use case.

Please try it out and let me know.  Cheers!

**Comment by kmsquire** [comment]
PR: https://github.com/kmsquire/VideoIO.jl/pull/59

**Comment by kmsquire** [comment]
Done and (almost) tagged (waiting for travis to finish on METADATA.jl).

**Comment by SimonDanisch** [comment]
Great! Thanks a lot :)
