### ISSUE TITLE
Can't execute playvid.jl Tk.TclError

### ISSUE THREAD

**Issue by kendrick1501** [kmsquire/VideoIO.jl#89]
Hi guys!

I am a newbie in Julia programming, and I would like you to help me on this matter.

I am trying to run the "playvid.jl" file in a JuliaBox notebook with the following code:

```
Pkg.add("ImageView")
Pkg.add("Images")
include("playvid.jl")
```

After installation of the necessary packages with output:

**INFO: Cloning cache of BinDeps from https://github.com/JuliaLang/BinDeps.jl.git
INFO: Cloning cache of Cairo from https://github.com/JuliaGraphics/Cairo.jl.git
INFO: Cloning cache of Dates from https://github.com/quinnj/Dates.jl.git
INFO: Cloning cache of ImageView from https://github.com/timholy/ImageView.jl.git
INFO: Cloning cache of IniFile from https://github.com/JuliaIO/IniFile.jl.git
INFO: Cloning cache of SHA from https://github.com/staticfloat/SHA.jl.git
INFO: Cloning cache of Tk from https://github.com/JuliaGraphics/Tk.jl.git
INFO: Cloning cache of URIParser from https://github.com/JuliaWeb/URIParser.jl.git
INFO: Cloning cache of Winston from https://github.com/nolta/Winston.jl.git
INFO: Installing BinDeps v0.4.5
INFO: Installing Cairo v0.2.35
INFO: Installing Dates v0.4.4
INFO: Installing ImageView v0.2.0
INFO: Installing IniFile v0.2.5
INFO: Installing SHA v0.3.0
INFO: Installing Tk v0.4.0
INFO: Installing URIParser v0.1.7
INFO: Installing Winston v0.12.1
INFO: Building Cairo
INFO: Building Tk
INFO: Package database updated
INFO: Nothing to be done
INFO: Precompiling module Cairo.** 

The result is:

**LoadError: LoadError: LoadError: LoadError: LoadError: Tk.TclError("error initializing Tk: no display name and no \$DISPLAY environment variable")
while loading /home/juser/.julia/v0.5/Tk/src/tkwidget.jl, in expression starting on line 455
while loading /home/juser/.julia/v0.5/Tk/src/Tk.jl, in expression starting on line 37
while loading /home/juser/.julia/v0.5/ImageView/src/ImageView.jl, in expression starting on line 14
while loading /home/juser/VideoIO.jl/examples/playvid.jl, in expression starting on line 2
while loading In[5], in expression starting on line 3

 in init() at /home/juser/.julia/v0.5/Tk/src/tkwidget.jl:62
 in include_from_node1(::String) at ./loading.jl:488 (repeats 2 times)
 in eval(::Module, ::Any) at ./boot.jl:234
 in require(::Symbol) at ./loading.jl:415
 in include_from_node1(::String) at ./loading.jl:488
 in eval(::Module, ::Any) at ./boot.jl:234
 in require(::Symbol) at ./loading.jl:415
 in include_from_node1(::String) at ./loading.jl:488**

**Comment by kmsquire** [comment]
This doesn't look like a problem (specifically) with VideoIO. Would you mind reposting the question at https://discourse.julialang.org/, and adding information about what platform you're on and what version of Julia you're using?  Thanks!
