### ISSUE TITLE
MethodError: Cannot `convert` an object of type Ptr{Void} to an object of type Pipe

### ISSUE THREAD

**Issue by kendrick1501** [kmsquire/VideoIO.jl#90]
Hi guys!

I am struggling to run the test for VideoIO package.  I am using ATOM with Julia-0.5.0 on Windows 7.

From there I am executing "runtest.jl" but the error below comes out.

**LoadError: LoadError: MethodError: Cannot `convert` an object of type Ptr{Void} to an object of type Pipe**

**This may have arisen from a call to the constructor Pipe(...), since type constructors fall back to convert methods.**
 
**in open_stdout_stderr(::Cmd) at C:\Users\Kendrick\.julia\v0.5\VideoIO\src\util.jl:26**
**in readall_stdout_stderr(::Cmd) at C:\Users\Kendrick\.julia\v0.5\VideoIO\src\util.jl:47**
**in get_camera_devices(::String, ::String, ::String) at C:\Users\Kendrick\.julia\v0.5\VideoIO\src\avio.jl:603**
**in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)**
**in eval(::Module, ::Any) at .\boot.jl:234**
**in require(::Symbol) at .\loading.jl:415**
**in include_string(::String, ::String) at .\loading.jl:441**
**in include_string(::String, ::String, ::Int64) at C:\Users\Kendrick\.julia\v0.5\CodeTools\src\eval.jl:28**
**in include_string(::Module, ::String, ::String, ::Int64, ::Vararg{Int64,N}) at** **C:\Users\Kendrick\.julia\v0.5\CodeTools\src\eval.jl:32**
**in (::Atom.##55#58{String,Int64,String})() at C:\Users\Kendrick\.julia\v0.5\Atom\src\eval.jl:40**
**in withpath(::Atom.##55#58{String,Int64,String}, ::String) at** **C:\Users\Kendrick\.julia\v0.5\CodeTools\src\utils.jl:30**
**in withpath(::Function, ::String) at C:\Users\Kendrick\.julia\v0.5\Atom\src\eval.jl:46**
**in macro expansion at C:\Users\Kendrick\.julia\v0.5\Atom\src\eval.jl:57 [inlined]**
**in (::Atom.##54#57{String,Int64,String})() at .\task.jl:60** 
**while loading C:\Users\Kendrick\.julia\v0.5\VideoIO\src\avio.jl,** 
**in expression starting on line 635**
**while loading C:\Users\Kendrick\.julia\v0.5\VideoIO\src\VideoIO.jl, in expression starting on line 13**

I manage to run it if I execute line by line of the require .jl's however, sometimes work sometimes not. When it does not work, it shows the error for the code `include("avio.jl")` in "VideoIO.jl"

**LoadError: invalid redefinition of constant AVInput**

**in include_from_node1(::String) at .\loading.jl:488**
 **in include_string(::String, ::String) at .\loading.jl:441**
 **in include_string(::String, ::String, ::Int64) at C:\Users\Kendrick\.julia\v0.5\CodeTools\src\eval.jl:28**
 **in include_string(::Module, ::String, ::String, ::Int64, ::Vararg{Int64,N}) at** **C:\Users\Kendrick\.julia\v0.5\CodeTools\src\eval.jl:32**
 **in (::Atom.##55#58{String,Int64,String})() at C:\Users\Kendrick\.julia\v0.5\Atom\src\eval.jl:40**
 **in withpath(::Atom.##55#58{String,Int64,String}, ::String) at** **C:\Users\Kendrick\.julia\v0.5\CodeTools\src\utils.jl:30**
 **in withpath(::Function, ::String) at C:\Users\Kendrick\.julia\v0.5\Atom\src\eval.jl:46**
 **in macro expansion at C:\Users\Kendrick\.julia\v0.5\Atom\src\eval.jl:57 [inlined]**
 **in (::Atom.##54#57{String,Int64,String})() at .\task.jl:60**
**while loading C:\Users\Kendrick\.julia\v0.5\VideoIO\src\avio.jl, in expression starting on line 29**

Hope you can help me through. Thanks!

**Comment by SimonDanisch** [comment]
Can you try:
https://github.com/kmsquire/VideoIO.jl/pull/91

It was a pretty weird bug fixing experience, since I couldn't find any trace of this working before?! I do remember using this a couple of weeks/months ago, so it must have been at least 0.4 (or 0.5 even).
@kmsquire do you know what is happening here?

**Comment by kendrick1501** [comment]
Simon thanks! It worked.
